### ISSUE TITLE
Unable to update using EfRepository UpdateAsync Method

### ISSUE THREAD

**Issue by Aman-US-Punjabi** [ardalis/Specification#129] opened 2021-06-01 23:57 UTC
Error: The instance of entity type 'DemoEntityTypeName' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.

I'm able to get and add methods with no issue but when I tried to use update, it gives me this error.

I'm using it in a Razor partial class, where I retrieve Entity by id OnInitializedAsync by using GetByIdAsync method and updating the Entity in HandleUpdateMethod using UpdateAsync method of EfRepository

I followed the link below
https://ardalis.github.io/Specification/getting-started/quick-start-guide.html

Please help me fix this error.

What I'm doing:
1. In Razor Partial class, get Entity from Database using Id in the parameter
2. Using Automapper to map the Entity to DTO
3. After update button pressed ( Map DTO to Entity and pass this mapped Entity to update Service method).
---------
Error goes away when I follow these steps at the place of above steps:

1. In Razor Partial class, get Entity from Database using Id in the parameter
2. Using Automapper to map the Entity to DTO
3. After update button pressed ( Map DTO to Entity and pass this mapped Entity to update Service method).
4. In Update Service Method ( get the Entity from Database using Id of the Entity passed to this method, updating the properties of this Entity which I get from db and passing this Entity to UpdateAsync method at the place of Entity passed to the UpdateService Method)
5. Manually updating each property after getting Entity from Db don't make sense. Why not I'm able to pass Entity which is passed to this method from the Razor page class)?

**Comment by fiseni** [comment] 2021-06-02 15:57
Hi @Aman-US-Punjabi,

This is not directly related to the `Specification` package, but it has to do with the change tracker of EF, and the way you're using it.
There are two options/ways how to do handle the `Update` actions
- Fetch the entity from EF, do the corresponding changes to that particular object, and save the changes.
- Create new entity object, fill with the corresponding info, fill the `Id` too, and call `Update` method. But, if you're doing this way, it's crucial that you don't fetch the entity from DB. If previously you already fetched an entity with the same Id through EF (within the same scope), now EF has 2 objects with the same Id in the tracker and has no idea what to do. Which of them should be considered relevant? That's the issue in a nutshell.

If you're doing automatic reverse mapping with Automapper, then you can provide existing object instead of letting Automapper create new destination object for you. It should be something like `_mapper.Map<CustomerDto, Customer>(customerDtoObject, customerEntityObjectFetchedThroughEF)`.

**Comment by Aman-US-Punjabi** [comment] 2021-06-02 21:25
Hi @fiseni,

Thanks for the help. 

"If you're doing automatic reverse mapping with Automapper, then you can provide existing object instead of letting Automapper create new destination object for you. It should be something like _mapper.Map<CustomerDto, Customer>(customerDtoObject, customerEntityObjectFetchedThroughEF)."

Solved the error, I hope this is the best way to fix the issue which I'm facing.

**Comment by ardalis** [comment] 2021-06-04 20:42
Looks like I can close this. One other comment I have based on your description of the problem is that perhaps you don't have your DbContext lifetime configured as Scoped, but perhaps as Singleton/Transient and that could cause the problem as well if you're working with the entity in two different parts of your application that are each constructed separately with their own instance of the DbContext.

**Closed by ardalis** 2021-06-04 20:42 UTC
