### ISSUE TITLE
How to get an empty specification?

### ISSUE THREAD

**Issue by sdudnic** [ardalis/Specification#76] opened 2021-02-01 13:01 UTC
Is it possible to create a default empty specification that does nothing?

https://stackoverflow.com/questions/65992960/how-to-get-an-empty-specification-that-does-not-filter-or-do-something

PS. I created a

```
    public class EmptySpecification<T> : Specification<T>
    {
        public EmptySpecification()
        {
            // does nothing
        }
    }

```

**Comment by fiseni** [comment] 2021-02-02 12:56
Having an empty specification is a totally valid construct. Once evaluated will return all records. In the below example, it will return all customers

```c#
public class CustomerSpec : Specification<Customer>
{
    public CustomerSpec()
    {
    }
}
```

But, in the question you posted in SO, the issue is not the empty specification. You're trying to add another layer of abstraction, and you're trying to instantiate `Specification<T>` directly. The `Specification` is an abstract class, thus you won't be able to create an instance. If you are eager to implement that infrastructure, then just add your own base class inherited from `Specification<T>`, and then use that one as a base for all the other specifications in your app.

```c#
public class AppSpecification<T> : Specification<T>
{
}
```

**Comment by fiseni** [comment] 2021-02-03 19:38
Hey @sdudnic,
Since the issue is resolved for you (details in the SO link), then I'm closing the issue here.

**Closed by fiseni** 2021-02-03 19:38 UTC

**Comment by sdudnic** [comment] 2021-02-11 10:23
> Hey @sdudnic,
> Since the issue is resolved for you (details in the SO link), then I'm closing the issue here.

I mean, maybe there's a way to implement that in the framework directly, in order the users do not create generic Empty specifications by themselves

**Comment by fiseni** [comment] 2021-02-11 17:01
The `Specification` base class in the package is defined as abstract by design. It was a deliberate decision. We want to discourage the users to instantiate it directly. For an instance, the following statement `new Specification<Customer>` has no value whatsoever.  There is no query defined, does not have a friendly name, you have no opportunity to add queries later on, etc.

On the other hand, if you want to add additional abstractions on top of it and create an infrastructure that fits your requirements, then all you have to do is define your own non-abstract base specification. That's all.

```c#
public class AppSpecification<T> : Specification<T>
{
}
```
