### ISSUE TITLE
How to implement dynamic linq for Query.OrderBy and Query.Where

### ISSUE THREAD

**Issue by dcadlereii** [ardalis/Specification#154] opened 2021-09-15 19:07 UTC
I would like to be able to pass strings that represent table fields from my client into my API where I have the ardalis.Specification nuget installed. @ardalis had recommended that I review suggestions in a StackOverflow post here: https://stackoverflow.com/questions/2728340/how-can-i-do-an-orderby-with-a-dynamic-string-parameter and 
reviewing the SO post led me to the System.Linq.Dynamic.Core nuget package that looked like it would allow me to achieve my goal with some extension methods.

I installed the System.Linq.Dynamic.Core nuget on my API and added the using statement in my Specification class, but then when I try to pass a string into the Query.OrderBy(stringVariable) I get the following error;

CS1929: 'ISpecificationBuilder<Orgnization>' does not contain a definition for 'OrderBy' and the best extension method overload 'DynamicQueryableExtensions.OrderBy(IQueryable, string, params object[])' requires a receiver of type IQueryable'

Here is my current spec class;

```
using System.Linq;
using System.Linq.Dynamic.Core;  //<--  added
using Ardalis.Specification;
using CD.Admin.Core.Aggregates.Organizations.Entities;
using CD.Admin.Core.Aggregates.Organizations.Specifications.Filters;
using CD.SharedKernal.Helpers;

namespace CD.Admin.Core.Aggregates.Organizations.Specifications
{
    public class OrganizationListSpec : Specification<Organization>
    {
        public OrganizationListSpec(OrganizationFilter spec)
        {
            if (!string.IsNullOrEmpty(spec.OrderBy))
            {
                Query.OrderBy(spec.OrderBy); // <-- spec.OrderBy is a string that represents the field name. 
            }

            if (spec.IsPagingEnabled)
            {
                Query.Skip(PaginationHelper.CalculateSkip(spec))
                     .Take(PaginationHelper.CalculateTake(spec));
            }

            if (!string.IsNullOrEmpty(spec.Filter))
            {
                Query.Where(x => x.Name.Contains(spec.Filter) || x.OrganizationId.Contains(spec.Filter));  //<-- I would also like to use dynamics here, if possible.
            }
        }
    }
}


```

In my use case, the client for my API will be a Blazor WASM that uses a SyncFusion Blazor Grid. The grid allows the potential for the user to sort and filter on every column. I would like to support this flexibility in my API but I don't want to have to code each possible individual table field for every table that will have its paged data exposed in a Grid component. Being able to simply pass the string representation of a table field would be a big benefit toward my desired use case if I can figure out how to correctly apply it to my spec.

Can anyone tell me if this is actually possible with the ardalis.Specification nuget and if so, recommend a way to make this work correctly and/or provide an example?

**Comment by ardalis** [comment] 2021-09-15 21:29
@fiseni have you done dynamic order-by at all? Seems like something that might be a common request for specifications. Thoughts?

**Comment by fiseni** [comment] 2021-09-15 21:35
I provided an extension in the following issue #53.
We can include it OOTB. But, there is always "but" :). How about if you use value objects in your entities, then you should care for scanning nested types. I have something for that, that I use for my own projects. But, it becomes too speecific.

**Comment by dcadlereii** [comment] 2021-09-16 14:54
Thanks @fiseni and @ardalis. I implemented the extension method provided by @lankymart in issue #53 and it seems to be doing exactly what I wanted.

**Comment by ardalis** [comment] 2021-09-16 16:57
This does seem to be almost a duplicate of #53. I'll add an issue for us to document this in our docs.

**Closed by ardalis** 2021-09-16 16:57 UTC

**Comment by davidhenley** [comment] 2021-09-16 17:23
I was just about to ask the same question! You guys are on top of it!

**Comment by davidhenley** [comment] 2021-09-16 17:28
Would also love a way to add whether the order should be ascending or descending like in DynamicaLINQ

**Comment by dcadlereii** [comment] 2021-09-16 20:05
@davidhenley the solution that  @lankymart listed in issue #53 uses a comma separated string value for the list of OrderBy fields and if you prefix a - in front of the string field name, for example;  "Name, -City", it does the OrderBy(Name) and then OrderByDescending(City). Seems to work well for me, so far.

**Comment by davidhenley** [comment] 2021-09-16 20:09
Thanks @dcadlereii, I am using his extension and it is working well.

Only thing that I could use now is a dictionary that maps the strings to lambda functions.

Example: "customerType": x => x.CustomerType.Name
