### ISSUE TITLE
Why use two containers to run integration tests?

### ISSUE THREAD

**Issue by lamelyan** [ardalis/Specification#299] opened 2022-11-14 14:38 UTC
For the[ integration tests in the build pipeline](https://ardalis.com/running-integration-tests-in-build-pipelines-with-a-real-database/), you use two containers. One that has integration tests and another for the database. 

This introduces complexity where you have to:

1. copy source files from the agent to the docker image
2. configure containers to talk to each other
3. copy test results created in the container to the agent so they can be displayed in the pipeline

Question: Why not create one container for the database and run tests directly on the agent/host machine?

**Comment by fiseni** [comment] 2023-02-11 19:20
Hi @lamelyan,

We've done it long ago, and never bothered to change it. We'll accept PRs improving the test infrastructure.

**Comment by fiseni** [comment] 2023-02-27 13:48
I was just about to create a pipeline for a different solution, and I got reminded of this issue. @ardalis do you remember why we didn't set a single container (only for the database)? Is it just so we can wait for the database to be up and ready? And to do that, we had to run the tests in the container too, right?

**Comment by ardalis** [comment] 2023-02-27 20:03
Yeah, it was a long time ago and I think the reason was mainly ignorance on my part. There were docs and samples showing how to get a SQL docker image, and there were docs/samples on how to get a dotnet image, and it was easy enough to use docker-compose or whatever to make the two talk. I wasn't aware of a stock docker image that had both (if there is one), nor did I want to figure out how to configure a container with both, so here we are...

**Comment by fiseni** [comment] 2023-02-27 21:14
No, I think the question was more about why not just run the mssql-ubuntu image, and then run the tests from the agent (just connect to db). And I think the issue is that once the db container is up and running, the build task is considered done and moves to the next one, the testing one. But, at that stage even though the container is up, not necessarilly the db is up and ready.

So, you need some mechanism to wait for the db to be ready. Either you will have some bash script that loops until the db connection is ready, or use the approach in this project.

Here I found a nice article that describes both approaches https://alex-klaus.com/dotnet-sql-tests/

Anyhow, I don't see a huge benefit of changing the approach in this project. I'm closing the issue.

**Closed by fiseni** 2023-02-27 21:14 UTC
